# Generated by Django 4.2.16 on 2025-01-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintwaleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='finish',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service_detail_title',
            field=models.CharField(default='NA', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(upload_to='services_images/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services_details_images/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail_images', to='paintwaleapp.service'),
        ),
    ]
