# Generated by Django 4.2.17 on 2025-01-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0002_serviceimage_finish_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="service",
            table="service",
        ),
        migrations.AlterModelTable(
            name="serviceimage",
            table="service_image",
        ),
    ]
