# Generated by Django 4.2.17 on 2025-01-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0006_process_active_product_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
