# Generated by Django 4.2.17 on 2025-01-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0007_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="brand_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="paintwaleapp.productbrand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
