# Generated by Django 4.2.17 on 2025-01-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0008_product_brand_product_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Walls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wall_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("active", models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                "db_table": "walls",
                "managed": True,
            },
        ),
    ]
