# Generated by Django 4.2.17 on 2025-01-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0009_walls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("otp", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "email_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("active", models.BooleanField(blank=True, default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
