# Generated by Django 4.2.17 on 2025-01-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0011_city_pricelist_pricelist_unique_process_product_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="email_id",
            new_name="email",
        ),
    ]
