# Generated by Django 4.2.17 on 2025-01-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0012_rename_email_id_users_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
