# Generated by Django 4.2.17 on 2025-01-14 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0015_lead_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="city",
            field=models.ForeignKey(
                db_column="city_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="paintwaleapp.city",
            ),
            preserve_default=False,
        ),
    ]
