# Generated by Django 4.2.17 on 2025-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0017_room_roomtype_wall_room_roomtype_quotationitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
