# Generated by Django 4.2.17 on 2025-01-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0018_lead_lead_date_lead_lead_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="total_price",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
