# Generated by Django 4.2.17 on 2025-01-14 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0019_quotationitem_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_value",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("discount", models.FloatField(blank=True, default=None, null=True)),
                ("status", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "quote_sent",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="createdfinalquotation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        db_column="lead_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="paintwaleapp.lead",
                    ),
                ),
                (
                    "quotation",
                    models.OneToOneField(
                        db_column="quotation_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="paintwaleapp.quotation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updatedfinalquotation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "final_quotation",
                "managed": True,
            },
        ),
    ]
