# Generated by Django 4.2.17 on 2025-01-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0020_finalquotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalquotation",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="brand_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="paintwaleapp.productbrand",
            ),
        ),
    ]
