# Generated by Django 4.2.17 on 2025-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintwaleapp", "0021_finalquotation_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalquotation",
            name="status",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
